spring.application.name=student-management
# Th\u00f4ng tin k\u1ebft n\u1ed1i l\u1ea5y t\u1eeb \u1ea3nh c\u1ee7a b\u1ea1n
spring.datasource.url=jdbc:postgresql://db.xozlvjdqeymffhkatqoa.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=4wObt40K1ZGRPIBB
spring.datasource.driver-class-name=org.postgresql.Driver

# C\u1ea5u h\u00ecnh Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always